import cidades from '@/lib/cidades.json';
import bancos from '@/lib/bancos.json';

export type FieldItemT = {
  value: string;
  label: string;
}

export const fieldItems: { [key: string] : FieldItemT[] } = {
  state: Object.keys(cidades).map((e) => ({ label: e, value: e })),
  bank: bancos.map((e) => ({ label: e, value: e })),
  tax_payer: [
    { label: 'Não Informado', value: 'unknown' },
    { label: 'Contribuinte isento de inscrição no cadastro de contribuintes do ICMS', value: 'yes' },
    { label: 'Não Contribuinte, que pode ou não possuir inscrição estadual no cadastro ICMS', value: 'no' },
  ],
  pricing: [
    { label: '$', value: '1' },
    { label: '$$', value: '2' },
    { label: '$$$', value: '3' },
    { label: '$$$$', value: '4' },
    { label: '$$$$$', value: '5' }
  ],
  style: [
    { label: 'Contemporâneo', value: 'Contemporâneo' },
    { label: 'Clássico', value: 'Clássico' },
    { label: 'Rústico', value: 'Rústico' },
    { label: 'Moderno', value: 'Moderno' }
  ],
  ambient: [
    { label: 'Interno', value: 'internal' },
    { label: 'Externo', value: 'external' },
    { label: 'Int. e Externo', value: 'both' }
  ],
  priority: [
    { label: '1', value: '1' },
    { label: '2', value: '2' },
    { label: '3', value: '3' },
  ],
  origin: [
    { label: 'Whatsapp', value: 'Whatsapp' },
    { label: 'Instagram', value: 'Instagram' },
    { label: 'Indicação', value: 'Indicação' },
    { label: 'Facebook', value: 'Facebook' },
    { label: 'Feira/Evento', value: 'Feira/Evento' },
    { label: 'Telefone', value: 'Telefone' },
    { label: 'Site', value: 'Site' },
    { label: 'Anúncio Impresso', value: 'Anúncio Impresso' },
    { label: 'Loja Física', value: 'Loja Física' },
    { label: 'Google Orgânico', value: 'Google Orgânico' },
    { label: 'Outdoors', value: 'Outdoors' },
    { label: 'Parceria Comercial', value: 'Parceria Comercial' },
    { label: 'Reunião Presencial', value: 'Reunião Presencial' },
  ],
  client_type: [
    { label: 'Família', value: 'Família' },
    { label: 'Amigos', value: 'Amigos' },
    { label: 'Empresário', value: 'Empresário' },
    { label: 'Estudante', value: 'Estudante' },
    { label: 'Arquitetos/Designers', value: 'Arquitetos/Designers' },
    { label: 'Construtora', value: 'Construtora' },
    { label: 'Condomínio', value: 'Condomínio' },
    { label: 'Cliente Recorrente', value: 'Cliente Recorrente' },
    { label: 'Novo Cliente', value: 'Novo Cliente' },
    { label: 'Revendedor', value: 'Revendedor' },
    { label: 'Cliente Corporativo', value: 'Cliente Corporativo' },
    { label: 'ONG/Instituição', value: 'ONG/Instituição' },
    { label: 'Parceiro Comercial', value: 'Parceiro Comercial' },
  ],
  project_type: [
    { label: 'Casa', value: 'Casa' },
    { label: 'Apartamento', value: 'Apartamento' },
    { label: 'Prédio', value: 'Prédio' },
    { label: 'Loja', value: 'Loja' },
    { label: 'Escritório', value: 'Escritório' },
    { label: 'Consultório', value: 'Consultório' },
    { label: 'Restaurante', value: 'Restaurante' },
    { label: 'Hotel', value: 'Hotel' },
    { label: 'Pousada', value: 'Pousada' },
    { label: 'Chácara', value: 'Chácara' },
    { label: 'Fazenda', value: 'Fazenda' },
    { label: 'Academia', value: 'Academia' },
    { label: 'Salão de Beleza', value: 'Salão de Beleza' },
    { label: 'Espaço de Eventos', value: 'Espaço de Eventos' },
    { label: 'Área Comum de Condomínio', value: 'Área Comum de Condomínio' },
    { label: 'Quarto de Hotel', value: 'Quarto de Hotel' },
    { label: 'Consultório Médico', value: 'Consultório Médico' },
    { label: 'Estúdio', value: 'Estúdio' },
    { label: 'Showroom', value: 'Showroom' },
    { label: 'Escola', value: 'Escola' },
  ],
  status_proposal: [
    { label: 'Perdido', value: '0' },
    { label: 'Solicitado', value: '1' },
    { label: 'Enviado', value: '2' },
    { label: 'Revisão', value: '3' },
    { label: 'Esperando', value: '4' },
    { label: 'Fechado', value: '5' },
  ],
  product_ambient: [
    { label: 'Cozinha', value: 'Cozinha' },
    { label: 'Sala de Estar', value: 'Sala de Estar' },
    { label: 'Quarto', value: 'Quarto' },
    { label: 'Banheiro', value: 'Banheiro' },
    { label: 'Sala de Jantar', value: 'Sala de Jantar' },
    { label: 'Home Office', value: 'Home Office' },
    { label: 'Varanda', value: 'Varanda' },
    { label: 'Área de Serviço', value: 'Área de Serviço' },
    { label: 'Hall de Entrada', value: 'Hall de Entrada' },
    { label: 'Closet', value: 'Closet' },
    { label: 'Garagem', value: 'Garagem' },
    { label: 'Jardim', value: 'Jardim' },
    { label: 'Terraço', value: 'Terraço' },
    { label: 'Sala de TV', value: 'Sala de TV' },
    { label: 'Porão', value: 'Porão' },
    { label: 'Sótão', value: 'Sótão' },
    { label: 'Espaço Gourmet', value: 'Espaço Gourmet' },
    { label: 'Academia', value: 'Academia' },
    { label: 'Biblioteca', value: 'Biblioteca' },
    { label: 'Sala de Jogos', value: 'Sala de Jogos' },
  ],
  product_category: [
    { label: 'Sofá', value: 'Sofá' },
    { label: 'Mesa', value: 'Mesa' },
    { label: 'Cadeira', value: 'Cadeira' },
    { label: 'Cama', value: 'Cama' },
    { label: 'Guarda-roupa', value: 'Guarda-roupa' },
    { label: 'Estante', value: 'Estante' },
    { label: 'Rack', value: 'Rack' },
    { label: 'Painel', value: 'Painel' },
    { label: 'Criado-mudo', value: 'Criado-mudo' },
    { label: 'Aparador', value: 'Aparador' },
    { label: 'Puff', value: 'Puff' },
    { label: 'Poltrona', value: 'Poltrona' },
    { label: 'Banco', value: 'Banco' },
    { label: 'Cômoda', value: 'Cômoda' },
    { label: 'Mesa de Centro', value: 'Mesa de Centro' },
    { label: 'Mesa Lateral', value: 'Mesa Lateral' },
    { label: 'Prateleira', value: 'Prateleira' },
    { label: 'Cama Box', value: 'Cama Box' },
    { label: 'Cabeceira', value: 'Cabeceira' },
    { label: 'Bar', value: 'Bar' },
    { label: 'Mesa de Jantar', value: 'Mesa de Jantar' },
    { label: 'Berço', value: 'Berço' },
    { label: 'Balcão', value: 'Balcão' },
    { label: 'Armário', value: 'Armário' },
    { label: 'Toucador', value: 'Toucador' },
    { label: 'Sapateira', value: 'Sapateira' },
    { label: 'Home Theater', value: 'Home Theater' },
    { label: 'Escrivaninha', value: 'Escrivaninha' },
    { label: 'Estação de Trabalho', value: 'Estação de Trabalho' },
    { label: 'Buffet', value: 'Buffet' },
  ],
  payment_method: [
    { label: 'Dinheiro', value: 'cash' },
    { label: 'Cartão de Débito', value: 'debit' },
    { label: 'Cartão de Crédito', value: 'credit' },
    { label: 'Boleto', value: 'bankslip' },
    { label: 'Pix', value: 'pix' },
  ],
} as const;